### ISSUE TITLE
Migrate to Focal Fossa (20.04) when stable version is released.

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida-prerequisites#20]
The alpha release of Focal Fossa image is [already available](https://github.com/phusion/baseimage-docker/releases/tag/focal-1.0.0-alpha1). However, it is better to wait until the stable version is released.

**Comment by ltalirz** [comment]
As of Feb 2021, there's still only an alpha release of the phusion baseimage out and they're not in a hurry to update https://github.com/phusion/baseimage-docker/issues/573

**Comment by greschd** [comment]
Since the current image uses Python 3.7, the deadline for this is `2021-12-26` according to [our support table](https://github.com/aiidateam/AEP/tree/master/003_adopt_nep_29#detailed-explanation).

Of course, we can decide to either go with the alpha version, or just manually update the Python which is used on the current image.

**Comment by yakutovicha** [comment]
> Since the current image uses Python 3.7, the deadline for this is `2021-12-26` according to [our support table](https://github.com/aiidateam/AEP/tree/master/003_adopt_nep_29#detailed-explanation).

I think that another argument to push them for making a stable release of Focal Fossa.

**Comment by greschd** [comment]
Well, Python 3.7 itself isn't EOL until 2023-06-27: https://devguide.python.org/#status-of-python-branches

And Ubuntu 18.04 is supported even longer: https://ubuntu.com/about/release-cycle

Not sure how much weight the scientific software stack has in this context.

**Comment by yakutovicha** [comment]
well, I tried to ask them...
