### ISSUE TITLE
Ansible role for Rabbitmq and PostgreSQL

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida-prerequisites#5]
Consider using ansible roles for rabbitmq / postgresql. If so, consider triggering new builds when ansible roles change.

**Comment by yakutovicha** [comment]
@ltalirz would you like to have a look at how to do it?

**Comment by ltalirz** [comment]
@espenfl has been hard at work since mid January to generalize the AiiDA ansible role at https://github.com/marvel-nccr/ansible-role-aiida to work with a variety of linux distros.

After lengthy investigations, he decided against using existing postgresql/rabbitmq roles, since they were not general enough.

For the moment, there is only one `aiida` role, and I suggest we keep it like this until Espen has completed the generalization.
We can later mirror the approach taken here, i.e. split the role into `aiida-prerequisites` and `aiida`, and then possibly have a go at reusing those roles inside the Dockerfiles for aiida-prerequisites/aiida-core.

Note: At this stage, I see this as a possibility, not as a necessity.
The Dockerfile tries to be as simple as possible and provide *one* standard working AiiDA environment.
The AiiDA ansible role tries to support the installation of AiiDA on a wider variety of platforms, including docker but also VMs and bare metal servers, with different Linux distros.

**Comment by espenfl** [comment]
@ltalirz @yakutovicha Indeed, I have been working a bit on this and it turned out to be more work than I expected. However, the aim is that we should be able to run it also in containers without `systemd` which complicates things a bit. Also, `SELinux` and `locale` issues emerged due to differences in available containers. I have been looking at Ubuntu, Fedora and CentOS. At some point we should consider to add also Arch for the vanilla people.

Once this is completed I believe isolating what happens until Rabbitmq and Postgresql is started should be straightforward.

**Comment by espenfl** [comment]
Please have a look at: https://github.com/marvel-nccr/ansible-role-aiida/issues/16#issuecomment-577866808

**Comment by yakutovicha** [comment]
We've discussed quite extensively the possibility to use Ansible to build Docker images (see https://github.com/aiidalab/aiidalab-docker-stack/issues/243) and the conclusion was to not use Ansible. Instead, we are going to install PGSQL and RMQ via conda. See #48 and #50 for more details.
