### ISSUE TITLE
Bug: only arm64 architecture is pushed to DockerHub.

### ISSUE THREAD

**Issue by yakutovicha** [aiidateam/aiida-prerequisites#54]
After #52 has been merged, only one architecture image is available on DockerHub (arm64):
![Screenshot 2022-07-28 154210](https://user-images.githubusercontent.com/13118485/181520411-0c89e9be-c310-450f-a39a-370c843969dc.png)

@unkcpz do you have an idea how this could be fixed?

**Comment by unkcpz** [comment]
I think this issue is exactly the same as we encountered https://github.com/docker/cli/issues/3350. Unfortunately, it is not supported by buildx to have different args for different platform. After some googling I think it worth to try the solution mentioned in the thread https://github.com/docker/cli/issues/3350#issuecomment-1084339451.

**Comment by unkcpz** [comment]
Please have a look at #55, it will solve the issue.

**Comment by unkcpz** [comment]
The problem that there is only one entity on dockerhub is caused by the second `build_and_push` will push with its own manifest list which doesn't include the manifest of the previous one. The buildx of `bulid_and_push` is supposed to handle creating a manifest list of multiple architectures.
